### ISSUE TITLE
添加语录会被其他用户发送的消息打断

### ISSUE THREAD

**Issue by XibieTime** [tsukishima1321/koishi-plugin-yulu#1]
群友A：添加语录
bot：请上传图片
群友B：玛卡巴卡····歪比巴伯···（无关消息）
群友A：[语录图片]

此时bot会没有任何反应。如果在bot提示请上传图片后，群友A立刻上传图片则能正常添加。

**Comment by tsukishima1321** [comment]
已在版本0.2.9修复
